import {test} from 'node:test';import assert from 'node:assert/strict';
import {adapters} from '../src/providers';import {providers,modelsFor} from '../src/providers/catalog';import {base64,unbase64} from '../src/providers/common';
import type {AdapterContext,GenerateRequest,ProviderId} from '../src/providers/types';import type {PhotonApi,NetworkRequest} from '@photon/plugin-sdk';
const image=Uint8Array.from([137,80,78,71]);
function fixture(provider:ProviderId,responses:any[]){const calls:NetworkRequest[]=[];const controller=new AbortController();const context:AdapterContext={credential:provider,job:{id:'job',signal:controller.signal,progress:async()=>{}},api:{network:{async request(options:NetworkRequest){calls.push(options);const body=responses.shift();if(body===undefined)throw new Error('Unexpected request: '+options.url);return {status:200,headers:{},body};}}} as unknown as PhotonApi};return {context,calls,controller};}
const input={png:image,whiteMask:Uint8Array.from([1]),alphaMask:Uint8Array.from([2]),width:1,height:1};
const request=(provider:ProviderId,edit=false):GenerateRequest=>({provider,model:modelsFor(providers.find(p=>p.id===provider)!,'generate')[0]?.id??'model',mode:edit?'fill':'generate',prompt:'a clean landscape',size:'1024x1024',quality:'auto',...(edit?{source:input}:{})});
for(const id of ['openai','custom','together'] as const)test(id+' decodes inline image output',async()=>{const f=fixture(id,[{data:[{b64_json:base64(image)}]}]);assert.deepEqual(await adapters[id].run(f.context,{...request(id==='custom'?'openai':id),provider:id}),image);assert.equal(f.calls.length,1);assert.equal(f.calls[0].credential?.id,id);});
test('OpenAI uses transparent-alpha multipart mask',async()=>{const f=fixture('openai',[{data:[{b64_json:base64(image)}]}]);await adapters.openai.run(f.context,request('openai',true));assert.deepEqual(f.calls[0].multipart?.find(p=>p.name==='mask')?.bytes,input.alphaMask);assert.match(f.calls[0].url,/images\/edits$/);});
test('Together passes source and mask references for prompt editing',async()=>{const f=fixture('together',[{data:[{b64_json:base64(image)}]}]);await adapters.together.run(f.context,request('together',true));assert.equal((f.calls[0].json as any).reference_images.length,2);});
test('Gemini iterates candidate parts and uses its key header',async()=>{const f=fixture('gemini',[{candidates:[{content:{parts:[{text:'done'},{inlineData:{mimeType:'image/png',data:base64(image)}}]}}]}]);assert.deepEqual(await adapters.gemini.run(f.context,request('gemini',true)),image);assert.equal(f.calls[0].credential?.header,'x-goog-api-key');assert.equal((f.calls[0].json as any).contents[0].parts.length,3);});
test('Gemini reports a blocked or text-only result',async()=>{const f=fixture('gemini',[{promptFeedback:{blockReason:'SAFETY'}}]);await assert.rejects(()=>adapters.gemini.run(f.context,request('gemini')),/declined/);});
test('fal submits once, polls queue, fetches output without a key',async()=>{const f=fixture('fal',[{status_url:'https://queue.fal.run/status',response_url:'https://queue.fal.run/result'},{status:'COMPLETED'},{images:[{url:'https://fal.media/image.png'}]},image]);assert.deepEqual(await adapters.fal.run(f.context,request('fal',true)),image);assert.equal(f.calls.filter(c=>c.method==='POST').length,1);assert.equal(f.calls[0].credential?.prefix,'Key ');assert.equal(f.calls.at(-1)?.credential,undefined);assert.equal((f.calls[0].json as any).mask_url,'data:image/png;base64,AQ==');});
test('Replicate submits a prediction and reads its output',async()=>{const f=fixture('replicate',[{status:'starting',urls:{get:'https://api.replicate.com/job'}},{status:'succeeded',output:['https://replicate.delivery/image.png']},image]);assert.deepEqual(await adapters.replicate.run(f.context,request('replicate',true)),image);assert.equal((f.calls[0].json as any).input.mask,'data:image/png;base64,AQ==');assert.equal(f.calls.at(-1)?.credential,undefined);});
test('BFL uses its API key header and supplied polling URL',async()=>{const f=fixture('bfl',[{id:'1',polling_url:'https://api.bfl.ai/result'},{status:'Ready',result:{sample:'https://delivery.bfl.ai/result.png'}},image]);assert.deepEqual(await adapters.bfl.run(f.context,{...request('bfl',true),model:'flux-pro-1.0-fill'}),image);assert.equal(f.calls[0].credential?.header,'x-key');assert.equal(f.calls[1].url,'https://api.bfl.ai/result');assert.equal((f.calls[0].json as any).mask,'AQ==');});
test('Provider errors are surfaced without submitting again',async()=>{const f=fixture('openai',[]);(f.context.api.network as any).request=async(p:NetworkRequest)=>{f.calls.push(p);return {status:429,body:{error:{message:'Quota exhausted'}},headers:{}};};await assert.rejects(()=>adapters.openai.run(f.context,request('openai')),/Quota exhausted/);assert.equal(f.calls.length,1);});
test('Cancellation prevents submission',async()=>{const f=fixture('together',[]);f.controller.abort();await assert.rejects(()=>adapters.together.run(f.context,request('together')));assert.equal(f.calls.length,0);});
test('BFL failures do not create another job',async()=>{const f=fixture('bfl',[{id:'1',polling_url:'https://api.bfl.ai/result'},{status:'Content Moderated'}]);await assert.rejects(()=>adapters.bfl.run(f.context,request('bfl')),/Moderated/);assert.equal(f.calls.filter(c=>c.method==='POST').length,1);});
test('Catalog filters unsupported model operations',()=>{for(const provider of providers.filter(p=>p.id!=='custom')){assert.ok(modelsFor(provider,'generate').every(m=>m.generate));assert.ok(modelsFor(provider,'fill').every(m=>m.edit));assert.ok(modelsFor(provider,'fill').length,'provider has at least one editing model');}assert.equal(providers.length,7);});
test('Binary conversion preserves full byte range',()=>{const values=Uint8Array.from({length:256},(_,i)=>i);assert.deepEqual(unbase64(base64(values)),values);});
for(const id of ['openai','gemini','together','fal','replicate','bfl'] as const){
 test(id+' stops before submission after cancellation',async()=>{const f=fixture(id,[]);f.controller.abort();await assert.rejects(()=>adapters[id].run(f.context,request(id)));assert.equal(f.calls.length,0);});
 test(id+' surfaces authentication and unavailable-model errors without retries',async()=>{for(const status of [401,404]){const f=fixture(id,[]);f.context.api.network.request=async options=>{f.calls.push(options);return {status,headers:{},body:{error:{message:status===401?'Invalid API key':'Model unavailable'}}} as any;};await assert.rejects(()=>adapters[id].run(f.context,request(id)),status===401?/Invalid API key/:/Model unavailable/);assert.equal(f.calls.length,1);}});
}
test('custom endpoints omit unsupported size and quality fields',async()=>{const f=fixture('custom',[{data:[{b64_json:base64(image)}]}]);await adapters.custom.run(f.context,{...request('openai'),provider:'custom',size:'',quality:'',baseUrl:'https://custom.example/v1'});assert.equal(f.calls[0].url,'https://custom.example/v1/images/generations');assert.equal('size' in (f.calls[0].json as any),false);assert.equal('quality' in (f.calls[0].json as any),false);});
for(const id of ['fal','replicate'] as const)test(id+' attempts remote cancellation after a queued job is aborted',async()=>{
 const f=fixture(id,id==='fal'?[{status_url:'https://queue.fal.run/status',response_url:'https://queue.fal.run/result',cancel_url:'https://queue.fal.run/cancel'},{status:'IN_PROGRESS'},{}]:[{status:'starting',urls:{get:'https://api.replicate.com/get',cancel:'https://api.replicate.com/cancel'}},{status:'processing'},{}]);
 f.context.job.progress=async()=>{f.controller.abort();};await assert.rejects(()=>adapters[id].run(f.context,request(id)));assert.equal(f.calls.filter(c=>c.method==='POST').length,2);assert.match(f.calls.at(-1)!.url,/cancel$/);assert.equal(f.calls.at(-1)!.jobId,undefined);
});
test('malformed output fails before creating a preview',async()=>{const f=fixture('openai',[{data:[{}]}]);await assert.rejects(()=>adapters.openai.run(f.context,request('openai')),/no image/);});
