import {test} from 'node:test';import assert from 'node:assert/strict';
import {adapters} from '../src/providers';import {providers,modelsFor} from '../src/providers/catalog';import {base64,unbase64} from '../src/providers/common';import {ideogramMask} from '../src/providers/ideogram';import {startDeviceLogin,completeDeviceLogin} from '../src/providers/oauth';
import type {AdapterContext,GenerateRequest,ProviderId} from '../src/providers/types';import type {PhotonApi,NetworkRequest} from '@photon/plugin-sdk';
const image=Uint8Array.from([137,80,78,71]);
function fixture(provider:ProviderId,responses:any[]){const calls:NetworkRequest[]=[];const controller=new AbortController();const context:AdapterContext={credential:provider,job:{id:'job',signal:controller.signal,progress:async()=>{}},api:{network:{async request(options:NetworkRequest){calls.push(options);const body=responses.shift();if(body===undefined)throw new Error('Unexpected request: '+options.url);if(body&&typeof body==='object'&&!(body instanceof Uint8Array)&&Object.prototype.hasOwnProperty.call(body,'status')&&Object.prototype.hasOwnProperty.call(body,'body'))return {status:body.status,headers:{},body:body.body};return {status:200,headers:{},body};}}} as unknown as PhotonApi};return {context,calls,controller};}
const input={png:image,whiteMask:Uint8Array.from([1]),alphaMask:Uint8Array.from([2]),width:1,height:1};
const request=(provider:ProviderId,edit=false):GenerateRequest=>({provider,model:modelsFor(providers.find(p=>p.id===provider)!,'generate')[0]?.id??'model',mode:edit?'fill':'generate',prompt:'a clean landscape',size:'1024x1024',quality:'auto',...(edit?{source:input}:{})});
for(const id of ['openai','custom','together'] as const)test(id+' decodes inline image output',async()=>{const f=fixture(id,[{data:[{b64_json:base64(image)}]}]);assert.deepEqual(await adapters[id].run(f.context,{...request(id==='custom'?'openai':id),provider:id}),image);assert.equal(f.calls.length,1);assert.equal(f.calls[0].credential?.id,id);});
test('OpenAI uses transparent-alpha multipart mask',async()=>{const f=fixture('openai',[{data:[{b64_json:base64(image)}]}]);await adapters.openai.run(f.context,request('openai',true));assert.deepEqual(f.calls[0].multipart?.find(p=>p.name==='mask')?.bytes,input.alphaMask);assert.match(f.calls[0].url,/images\/edits$/);});
test('Together passes source and mask references for prompt editing',async()=>{const f=fixture('together',[{data:[{b64_json:base64(image)}]}]);await adapters.together.run(f.context,request('together',true));assert.equal((f.calls[0].json as any).reference_images.length,2);});
test('Gemini iterates candidate parts and uses its key header',async()=>{const f=fixture('gemini',[{candidates:[{content:{parts:[{text:'done'},{inlineData:{mimeType:'image/png',data:base64(image)}}]}}]}]);assert.deepEqual(await adapters.gemini.run(f.context,request('gemini',true)),image);assert.equal(f.calls[0].credential?.header,'x-goog-api-key');assert.equal((f.calls[0].json as any).contents[0].parts.length,3);assert.equal((f.calls[0].json as any).generationConfig.imageConfig.aspectRatio,'1:1');assert.equal((f.calls[0].json as any).generationConfig.imageConfig.imageSize,undefined);});
test('Gemini sends the selected aspect ratio and image size',async()=>{const f=fixture('gemini',[{candidates:[{content:{parts:[{inlineData:{mimeType:'image/png',data:base64(image)}}]}}]}]);await adapters.gemini.run(f.context,{...request('gemini'),model:'gemini-3.1-flash-image',size:'16:9',quality:'2K'});assert.deepEqual((f.calls[0].json as any).generationConfig.imageConfig,{aspectRatio:'16:9',imageSize:'2K'});const legacy=fixture('gemini',[{candidates:[{content:{parts:[{inlineData:{mimeType:'image/png',data:base64(image)}}]}}]}]);await adapters.gemini.run(legacy.context,{...request('gemini'),model:'gemini-2.5-flash-image',size:'1344x768',quality:'4K'});assert.equal((legacy.calls[0].json as any).generationConfig.imageConfig.aspectRatio,'16:9');assert.equal((legacy.calls[0].json as any).generationConfig.imageConfig.imageSize,undefined);});
test('Gemini reports a blocked or text-only result',async()=>{const f=fixture('gemini',[{promptFeedback:{blockReason:'SAFETY'}}]);await assert.rejects(()=>adapters.gemini.run(f.context,request('gemini')),/declined/);});
test('fal submits once, polls queue, fetches output without a key',async()=>{const f=fixture('fal',[{status_url:'https://queue.fal.run/status',response_url:'https://queue.fal.run/result'},{status:'COMPLETED'},{images:[{url:'https://fal.media/image.png'}]},image]);assert.deepEqual(await adapters.fal.run(f.context,request('fal',true)),image);assert.equal(f.calls.filter(c=>c.method==='POST').length,1);assert.equal(f.calls[0].credential?.prefix,'Key ');assert.equal(f.calls.at(-1)?.credential,undefined);assert.equal((f.calls[0].json as any).mask_url,'data:image/png;base64,AQ==');});
test('Replicate submits a prediction and reads its output',async()=>{const f=fixture('replicate',[{status:'starting',urls:{get:'https://api.replicate.com/job'}},{status:'succeeded',output:['https://replicate.delivery/image.png']},image]);assert.deepEqual(await adapters.replicate.run(f.context,request('replicate',true)),image);assert.equal((f.calls[0].json as any).input.mask,'data:image/png;base64,AQ==');assert.equal(f.calls.at(-1)?.credential,undefined);const generated=fixture('replicate',[{status:'succeeded',output:['https://replicate.delivery/image.png']},image]);await adapters.replicate.run(generated.context,{...request('replicate'),size:'16:9',quality:''});assert.equal((generated.calls[0].json as any).input.aspect_ratio,'16:9');assert.equal((generated.calls[0].json as any).input.output_quality,undefined);});
test('BFL uses its API key header and supplied polling URL',async()=>{const f=fixture('bfl',[{id:'1',polling_url:'https://api.bfl.ai/result'},{status:'Ready',result:{sample:'https://delivery.bfl.ai/result.png'}},image]);assert.deepEqual(await adapters.bfl.run(f.context,{...request('bfl',true),model:'flux-pro-1.0-fill'}),image);assert.equal(f.calls[0].credential?.header,'x-key');assert.equal(f.calls[1].url,'https://api.bfl.ai/result');assert.equal((f.calls[0].json as any).mask,'AQ==');});
test('Provider errors are surfaced without submitting again',async()=>{const f=fixture('openai',[]);(f.context.api.network as any).request=async(p:NetworkRequest)=>{f.calls.push(p);return {status:429,body:{error:{message:'Quota exhausted'}},headers:{}};};await assert.rejects(()=>adapters.openai.run(f.context,request('openai')),/Quota exhausted/);assert.equal(f.calls.length,1);});
test('Cancellation prevents submission',async()=>{const f=fixture('together',[]);f.controller.abort();await assert.rejects(()=>adapters.together.run(f.context,request('together')));assert.equal(f.calls.length,0);});
test('BFL failures do not create another job',async()=>{const f=fixture('bfl',[{id:'1',polling_url:'https://api.bfl.ai/result'},{status:'Content Moderated'}]);await assert.rejects(()=>adapters.bfl.run(f.context,request('bfl')),/Moderated/);assert.equal(f.calls.filter(c=>c.method==='POST').length,1);});
test('Catalog filters unsupported model operations',()=>{for(const provider of providers.filter(p=>p.id!=='custom')){assert.ok(modelsFor(provider,'generate').every(m=>m.generate));assert.ok(modelsFor(provider,'fill').every(m=>m.edit));if(provider.id!=='midjourney')assert.ok(modelsFor(provider,'fill').length,'provider has at least one editing model');}assert.equal(modelsFor(providers.find(p=>p.id==='midjourney')!,'fill').length,0);assert.deepEqual(providers.map(p=>p.id),['openai','codex','gemini','midjourney','ideogram','bfl','fal','replicate','together','xai','grok','custom']);});
test('Binary conversion preserves full byte range',()=>{const values=Uint8Array.from({length:256},(_,i)=>i);assert.deepEqual(unbase64(base64(values)),values);});
for(const id of ['openai','codex','gemini','together','fal','replicate','bfl','xai','grok','ideogram'] as const){
 test(id+' stops before submission after cancellation',async()=>{const f=fixture(id,[]);f.controller.abort();await assert.rejects(()=>adapters[id].run(f.context,request(id)));assert.equal(f.calls.length,0);});
 test(id+' surfaces authentication and unavailable-model errors without retries',async()=>{for(const status of [401,404]){const f=fixture(id,[]);f.context.api.network.request=async options=>{f.calls.push(options);return {status,headers:{},body:{error:{message:status===401?'Invalid API key':'Model unavailable'}}} as any;};await assert.rejects(()=>adapters[id].run(f.context,request(id)),status===401?/Invalid API key/:/Model unavailable/);assert.equal(f.calls.length,1);}});
}
test('custom endpoints omit unsupported size and quality fields',async()=>{const f=fixture('custom',[{data:[{b64_json:base64(image)}]}]);await adapters.custom.run(f.context,{...request('openai'),provider:'custom',size:'',quality:'',baseUrl:'https://custom.example/v1'});assert.equal(f.calls[0].url,'https://custom.example/v1/images/generations');assert.equal('size' in (f.calls[0].json as any),false);assert.equal('quality' in (f.calls[0].json as any),false);});
for(const id of ['fal','replicate'] as const)test(id+' attempts remote cancellation after a queued job is aborted',async()=>{
 const f=fixture(id,id==='fal'?[{status_url:'https://queue.fal.run/status',response_url:'https://queue.fal.run/result',cancel_url:'https://queue.fal.run/cancel'},{status:'IN_PROGRESS'},{}]:[{status:'starting',urls:{get:'https://api.replicate.com/get',cancel:'https://api.replicate.com/cancel'}},{status:'processing'},{}]);
 f.context.job.progress=async()=>{f.controller.abort();};await assert.rejects(()=>adapters[id].run(f.context,request(id)));assert.equal(f.calls.filter(c=>c.method==='POST').length,2);assert.match(f.calls.at(-1)!.url,/cancel$/);assert.equal(f.calls.at(-1)!.jobId,undefined);
});
test('malformed output fails before creating a preview',async()=>{const f=fixture('openai',[{data:[{}]}]);await assert.rejects(()=>adapters.openai.run(f.context,request('openai')),/no image/);});
test('Codex sends the signed-in token and account to the image route',async()=>{const f=fixture('codex',[{data:[{b64_json:base64(image)}]}]);assert.deepEqual(await adapters.codex.run(f.context,{...request('codex'),accessToken:'codex-token',accountId:'acct_1'}),image);assert.equal(f.calls[0].url,'https://chatgpt.com/backend-api/codex/images/generations');assert.equal((f.calls[0] as {authorization?:string}).authorization,'Bearer codex-token');assert.equal(f.calls[0].headers?.Authorization,undefined);assert.equal(f.calls[0].headers?.['ChatGPT-Account-Id'],'acct_1');assert.equal(f.calls[0].credential,undefined);assert.equal((f.calls[0].json as any).model,'gpt-image-2.5-flare');});
test('Codex edits with the source and mask reference',async()=>{const f=fixture('codex',[{data:[{b64_json:base64(image)}]}]);await adapters.codex.run(f.context,{...request('codex',true),accessToken:'codex-token'});assert.match(f.calls[0].url,/images\/edits$/);assert.equal((f.calls[0].json as any).images.length,2);});
test('X API uses an API key for the same image models as Grok',async()=>{const f=fixture('xai',[{data:[{b64_json:base64(image)}]}]);assert.deepEqual(await adapters.xai.run(f.context,{...request('xai'),size:'1024x1536'}),image);assert.equal(f.calls[0].url,'https://api.x.ai/v1/images/generations');assert.equal(f.calls[0].credential?.header,'Authorization');assert.equal(f.calls[0].headers?.Authorization,undefined);assert.equal((f.calls[0].json as any).aspect_ratio,'2:3');assert.equal((f.calls[0].json as any).model,'grok-imagine-image-2.0');});
test('Grok image models use aspect ratio and return inline bytes',async()=>{const f=fixture('grok',[{data:[{b64_json:base64(image)}]}]);assert.deepEqual(await adapters.grok.run(f.context,{...request('grok'),accessToken:'grok-token',size:'1536x1024',quality:'low@2k'}),image);assert.equal(f.calls[0].url,'https://api.x.ai/v1/images/generations');assert.equal((f.calls[0].json as any).aspect_ratio,'3:2');assert.equal((f.calls[0].json as any).quality,'low');assert.equal((f.calls[0].json as any).resolution,'2k');assert.equal((f.calls[0].json as any).model,'grok-imagine-image-2.0');assert.equal(f.calls[0].credential,undefined);const original=fixture('grok',[{data:[{b64_json:base64(image)}]}]);await adapters.grok.run(original.context,{...request('grok'),model:'grok-imagine-image',size:'9:16',quality:'2k'});assert.equal((original.calls[0].json as any).aspect_ratio,'9:16');assert.equal((original.calls[0].json as any).resolution,'2k');assert.equal((original.calls[0].json as any).quality,undefined);});
test('Grok edits through the images endpoint',async()=>{const f=fixture('grok',[{data:[{url:'https://imgen.x.ai/out.png'}]},image]);await adapters.grok.run(f.context,request('grok',true));assert.match(f.calls[0].url,/images\/edits$/);assert.equal((f.calls[0].json as any).images.length,2);assert.equal(f.calls[1].credential,undefined);});
test('Ideogram generates then downloads without the API key',async()=>{const f=fixture('ideogram',[{data:[{url:'https://cdn.ideogram.ai/out.png',is_image_safe:true}]},image]);assert.deepEqual(await adapters.ideogram.run(f.context,{...request('ideogram'),quality:'high'}),image);assert.equal(f.calls[0].credential?.header,'x-api-key');assert.equal(f.calls[1].credential,undefined);assert.equal((f.calls[0].json as any).size,'1024x1024');assert.equal((f.calls[0].json as any).quality,'high');const omitted=fixture('ideogram',[{data:[{url:'https://cdn.ideogram.ai/out.png',is_image_safe:true}]},image]);await adapters.ideogram.run(omitted.context,{...request('ideogram'),quality:'very_low'});assert.equal((omitted.calls[0].json as any).quality,undefined);});
test('Ideogram precise edit sends the prepared mask',async()=>{const f=fixture('ideogram',[{data:[{url:'https://cdn.ideogram.ai/out.png',is_image_safe:true}]},image]);await adapters.ideogram.run(f.context,{...request('ideogram',true),quality:'very_low'});assert.match(f.calls[0].url,/precise-edit\/ideogram-4-5$/);assert.deepEqual(f.calls[0].multipart?.find(part=>part.name==='mask')?.bytes,input.whiteMask);assert.equal(f.calls[0].multipart?.find(part=>part.name==='quality')?.text,'very_low');assert.equal(f.calls[0].multipart?.some(part=>part.name==='size'),false);});
test('Ideogram reports an unsafe image',async()=>{const f=fixture('ideogram',[{data:[{url:'https://cdn.ideogram.ai/out.png',is_image_safe:false}]}]);await assert.rejects(()=>adapters.ideogram.run(f.context,request('ideogram')),/declined/);});
test('Ideogram mask uses black for the selected region',()=>{const pixels=ideogramMask(Uint8Array.from([255,0]));assert.equal(pixels[0],0);assert.equal(pixels[4],255);assert.equal(pixels[3],255);});
test('Midjourney does not call a network API',async()=>{const f=fixture('midjourney',[]);await assert.rejects(()=>adapters.midjourney.run(f.context,request('midjourney')),/official image API/);assert.equal(f.calls.length,0);});
test('Codex device sign-in logs status and exchanges the code',async()=>{const payload=Buffer.from(JSON.stringify({'https://api.openai.com/auth':{chatgpt_account_id:'acct_1'}})).toString('base64url');const lines:string[]=[];const f=fixture('codex',[{user_code:'ABCD-EFGH',device_auth_id:'dev',interval:1,expires_in:90},{status:403,body:{}},{status:200,body:{authorization_code:'once',code_verifier:'verify'}},{access_token:'codex-access',refresh_token:'codex-refresh',expires_in:3600,id_token:'h.'+payload+'.s'}]);const pending=await startDeviceLogin(f.context,'codex',line=>lines.push(line));assert.equal(pending.userCode,'ABCD-EFGH');assert.equal(pending.verificationUri,'https://auth.openai.com/codex/device');assert.equal(f.calls[0].jobId,undefined);const session=await completeDeviceLogin(f.context,pending,line=>lines.push(line));assert.equal(session.accountId,'acct_1');assert.equal(lines[0],'Requesting a sign-in code…');assert.equal(lines.filter(line=>line==='Waiting for approval…').length>=1,true);assert.equal(lines.at(-1),'Signed in.');assert.equal(JSON.stringify(lines).includes('codex-access'),false);assert.equal((f.calls.at(-1) as {form?:Record<string,string>}).form?.grant_type,'authorization_code');});
test('Grok device sign-in uses the accounts page and token endpoint',async()=>{const lines:string[]=[];const f=fixture('grok',[{token_endpoint:'https://auth.x.ai/oauth2/token'},{user_code:'GROK-1',device_code:'device-secret',verification_uri:'https://auth.x.ai/oauth2/device',interval:1,expires_in:90},{status:400,body:{error:'authorization_pending'}},{status:200,body:{access_token:'grok-access',expires_in:30}}]);const pending=await startDeviceLogin(f.context,'grok',line=>lines.push(line));assert.equal(pending.verificationUri,'https://accounts.x.ai/oauth2/device');const session=await completeDeviceLogin(f.context,pending,line=>lines.push(line));assert.equal(session.accessToken,'grok-access');assert.equal(f.calls[2].url,'https://auth.x.ai/oauth2/token');assert.equal(lines.join(' ').includes('grok-access'),false);assert.equal(lines.join(' ').includes('device-secret'),false);});
test('A declined device sign-in does not start another login',async()=>{const f=fixture('codex',[{user_code:'ABCD-EFGH',device_auth_id:'dev',interval:1,expires_in:90},{status:400,body:{error:'access_denied'}}]);const pending=await startDeviceLogin(f.context,'codex');await assert.rejects(()=>completeDeviceLogin(f.context,pending),/declined/);assert.equal(f.calls.filter(call=>call.method==='POST').length,2);});
