import {test} from 'node:test';import assert from 'node:assert/strict';import {activate} from '../src/plugin';import type {PhotonApi,PanelModel,UiEvent,Capture} from '@photon/plugin-sdk';
function harness(){let handler:(event:UiEvent)=>void|Promise<void>=()=>{};let latest:PanelModel={controls:[]};const applied:any[]=[];const released:string[]=[];let selected=false,configured=false,requests=0;
 const capture:Capture={token:'capture',documentId:'doc',revision:3,bounds:{x:1,y:2,width:1,height:1},width:1,height:1,pixels:new Uint8Array([10,20,30,255]),mask:new Uint8Array([255])};
 const api={ui:{render:async(_panel:string,model:PanelModel)=>{latest=model;},onEvent:(callback:typeof handler)=>{handler=callback;return {dispose(){handler=()=>{};}};}},commands:{on:()=>({dispose(){}})},events:{subscribe:()=>({dispose(){}})},settings:{get:async()=>({}),set:async()=>{}},credentials:{status:async()=>({id:'openai',configured,persistent:true,origin:configured?'https://api.openai.com':undefined}),configure:async()=>{configured=true;return {id:'openai',configured,persistent:true,origin:'https://api.openai.com'};},delete:async()=>{configured=false;}},network:{request:async()=>{requests++;return {status:200,headers:{},body:{data:[{b64_json:'AQID'}]}};}},jobs:{run:async(_label:string,callback:any)=>callback({id:'job',signal:new AbortController().signal,progress:async()=>{}})},documents:{active:async()=>({id:'doc',revision:3,hasSelection:selected}),capture:async()=>capture,release:async(token:string)=>{released.push(token);},applyImage:async(value:any)=>{applied.push(value);return {documentId:'doc',layerId:'new'};}},images:{encode:async(image:any)=>({...image,bytes:new Uint8Array([137,80,78,71])}),decode:async()=>({width:1,height:1,pixels:new Uint8Array([1,2,3,255])})},files:{pick:async()=>null}} as unknown as PhotonApi;
 return {api,applied,released,get model(){return latest;},get requests(){return requests;},setSelected(value:boolean){selected=value;},event:async(id:string,value?:UiEvent['value'])=>handler({id,value,panel:'ai'})};}
test('generation remains in preview until Apply creates a new document',async()=>{const h=harness();const lifecycle=await activate(h.api);await h.event('configure');await h.event('prompt','A mountain');await h.event('run');assert.equal(h.requests,1);assert.equal(h.applied.length,0);assert.ok(h.model.controls.some(c=>c.type==='group'));await h.event('apply');assert.equal(h.applied[0].newDocument,true);lifecycle.dispose();});
test('fill carries its capture token and creates a masked edit only on Apply',async()=>{const h=harness();h.setSelected(true);await activate(h.api);await h.event('configure');await h.event('mode','fill');await h.event('prompt','A garden');await h.event('run');assert.equal(h.applied.length,0);await h.event('apply');assert.equal(h.applied[0].captureToken,'capture');assert.equal(h.applied[0].newDocument,false);assert.equal(h.applied[0].name,'Generative Fill');});
test('discard releases the capture without applying pixels',async()=>{const h=harness();h.setSelected(true);await activate(h.api);await h.event('configure');await h.event('mode','remove');await h.event('run');await h.event('discard');assert.deepEqual(h.released,['capture']);assert.equal(h.applied.length,0);});
test('selection modes show a disabled action when no selection exists',async()=>{const h=harness();await activate(h.api);await h.event('configure');await h.event('mode','fill');await h.event('prompt','garden');assert.equal(h.model.controls.find(c=>c.id==='run')?.disabled,true);});
test('insert generation pins the target document and revision',async()=>{const h=harness();await activate(h.api);await h.event('configure');await h.event('prompt','Landscape');await h.event('insert',true);await h.event('run');await h.event('apply');assert.equal(h.applied[0].documentId,'doc');assert.equal(h.applied[0].expectedRevision,3);assert.equal(h.applied[0].newDocument,false);});
test('a stale Apply keeps the preview and offers regeneration',async()=>{const h=harness();h.setSelected(true);await activate(h.api);await h.event('configure');await h.event('mode','fill');await h.event('prompt','garden');await h.event('run');h.api.documents.applyImage=async()=>{throw new Error('Document changed. Regenerate before applying.');};await h.event('apply');assert.ok(h.model.controls.some(c=>c.type==='group'));assert.equal(h.model.controls.find(c=>c.id==='run')?.label,'Regenerate');assert.ok(h.model.controls.some(c=>c.tone==='danger'&&c.text?.includes('Document changed')));});

test('custom generation-only models disable unsupported edit actions',async()=>{const h=harness();h.setSelected(true);await activate(h.api);await h.event('provider','custom');await h.event('customModel','generation-only');await h.event('customEdit',false);await h.event('configure');await h.event('mode','fill');await h.event('prompt','garden');assert.equal(h.model.controls.find(c=>c.id==='run')?.disabled,true);assert.ok(h.model.controls.some(c=>c.text?.includes('does not support image editing')));assert.equal(h.requests,0);});
