import {PluginError,type NetworkRequest} from '@photon/plugin-sdk';
import type {AdapterContext} from './types';
export type WireRequest=NetworkRequest&{form?:Record<string,string>;authorization?:string};
export function base64(bytes:Uint8Array):string{let text='';for(let offset=0;offset<bytes.length;offset+=32768)text+=String.fromCharCode(...bytes.subarray(offset,offset+32768));return btoa(text);}
export function unbase64(value:string):Uint8Array{if(value.length>90*1024*1024)throw new PluginError('INVALID_RESULT','Image response is too large.');return Uint8Array.from(atob(value),c=>c.charCodeAt(0));}
export const dataUrl=(bytes:Uint8Array)=>'data:image/png;base64,'+base64(bytes);
export function dimensions(size:string){const [width,height]=size.split('x').map(Number);if(![width,height].every(v=>Number.isInteger(v)&&v>0&&v<=4096))throw new PluginError('INVALID_INPUT','Choose a supported image size.');return {width,height};}
export async function raw<T=any>(context:AdapterContext,options:WireRequest,tracked=true):Promise<{status:number;body:T}>{context.job.signal.throwIfAborted();const result=await context.api.network.request<T>({...options,...(tracked?{jobId:context.job.id}:{})});context.job.signal.throwIfAborted();return {status:result.status,body:result.body};}
export async function request<T=any>(context:AdapterContext,options:WireRequest,tracked=true):Promise<T>{const result=await raw<T>(context,options,tracked);if(result.status<200||result.status>=300){const value=result.body as any;const message=value?.error?.message??value?.detail??(typeof value?.error==='string'?value.error:undefined)??`Provider request failed (${result.status}).`;const code=result.status===401||result.status===403?'AUTHENTICATION':result.status===429?'QUOTA':result.status===404?'MODEL_UNAVAILABLE':'PROVIDER_ERROR';throw new PluginError(code,String(message).slice(0,1000));}return result.body;}
export const auth=(c:AdapterContext,header:'Authorization'|'x-api-key'|'x-goog-api-key'|'x-key'='Authorization',prefix?:string)=>({id:c.credential,header,...(prefix===undefined?{}:{prefix})});
export async function download(c:AdapterContext,value:unknown):Promise<Uint8Array>{if(typeof value!=='string'||!value)throw new PluginError('INVALID_RESULT','Provider returned no image.');if(value.startsWith('data:image/'))return unbase64(value.split(',')[1]);return request<Uint8Array>(c,{url:value,response:'bytes'});}
export async function wait(c:AdapterContext,ms=2000){c.job.signal.throwIfAborted();await new Promise<void>((resolve,reject)=>{const abort=()=>{clearTimeout(timer);reject(new PluginError('CANCELLED','Operation cancelled.'));};const timer=setTimeout(()=>{c.job.signal.removeEventListener('abort',abort);resolve();},ms);c.job.signal.addEventListener('abort',abort,{once:true});});}
export async function poll(c:AdapterContext,read:()=>Promise<any>,done:(value:any)=>unknown,failed:(value:any)=>string|undefined):Promise<unknown>{for(let n=0;n<150;n++){c.job.signal.throwIfAborted();const value=await read();const error=failed(value);if(error)throw new PluginError('PROVIDER_ERROR',error);const output=done(value);if(output)return output;await c.job.progress('Waiting for provider…');await wait(c);}throw new PluginError('TIMEOUT','Provider job timed out. Check its dashboard before submitting again.');}
export const REMOVE_PROMPT='Remove the selected object or content and reconstruct a natural, seamless background that matches the surroundings, lighting, texture, and perspective. Preserve everything outside the selected region. Do not add new objects.';
export const EDIT_GUIDANCE=' Edit only the region indicated by the white area in the mask reference. Black areas are context and must remain unchanged. Return the edited source image at the same composition, without drawing the mask.';
