import {PluginError} from '@photon/plugin-sdk';
import type {AdapterContext,Model,ProviderId} from './types';
import {providers} from './catalog';
import {applyOutputOptions,SIZE_PATTERN} from './output-options';
import {auth,request,type WireRequest} from './common';
export const MODEL_CACHE_MS=24*60*60*1000;
export interface ModelCacheEntry {fetchedAt:number;models:Model[];}
const LISTED=new Set<ProviderId>(['openai','codex','gemini','together','xai','grok','custom']);
const SIZES=['1024x1024','1536x1024','1024x1536'];
const QUALITIES=['auto','low','medium','high'];
export function listsModels(provider:ProviderId){return LISTED.has(provider);}
export function modelCacheStale(entry:ModelCacheEntry|undefined,now=Date.now()){return !entry||!entry.models.length||now-entry.fetchedAt>=MODEL_CACHE_MS;}
export function cachedBundledModels(provider:ProviderId,entry:ModelCacheEntry|undefined){const known=providers.find(item=>item.id===provider)?.models??[];return !!entry&&entry.models.length===known.length&&entry.models.every((model,index)=>model.id===known[index]?.id);}
function rows(body:any):any[]{if(Array.isArray(body))return body;const nested=body?.models?.data??body?.data?.models;if(Array.isArray(nested))return nested;if(Array.isArray(body?.data))return body.data;if(Array.isArray(body?.models))return body.models;if(Array.isArray(body?.image_models))return body.image_models;if(Array.isArray(body?.imageModels))return body.imageModels;return [];}
function modelId(row:any){return String(row?.id??row?.slug??row?.name??(typeof row?.model==='string'?row.model:'')).replace(/^models\//,'').trim();}
function safeId(id:string){return /^[\w./:+@-]{1,200}$/.test(id);}
function openAiImage(id:string){return /(?:^|\/)(gpt-image|chatgpt-image|dall-e)([-.]|$)/i.test(id);}
function modality(row:any,key:string){const mods=row?.[key]??row?.[key.replace(/_([a-z])/g,(_,letter)=>letter.toUpperCase())];return Array.isArray(mods)&&mods.some((item:unknown)=>String(item).toLowerCase()==='image');}
function emitsImage(row:any){return modality(row,'output_modalities');}
function acceptsImage(row:any){return modality(row,'input_modalities')||row?.supports_image_detail_original===true;}
function visibleModel(row:any){const visibility=String(row?.visibility??'list').toLowerCase();return visibility!=='hide'&&visibility!=='none';}
function geminiImage(id:string){return /image/i.test(id)&&!/^imagen/i.test(id);}
function togetherImage(row:any){return String(row?.type??'').toLowerCase()==='image';}
function grokImage(row:any,id:string){if(/video/i.test(id))return false;if(row?.image_price!=null||row?.generated_image_token_price!=null)return true;return /imagine-image/i.test(id);}
function keep(provider:ProviderId,row:any,id:string,allImage:boolean){if(!safeId(id)||!visibleModel(row))return false;if(provider==='xai'||provider==='grok')return allImage?!/video/i.test(id):grokImage(row,id);if(provider==='gemini')return geminiImage(id);if(provider==='together')return togetherImage(row);return openAiImage(id)||emitsImage(row)||acceptsImage(row);}
function defaults(provider:ProviderId,known:Model[]){const template=known.find(model=>model.generate)??known[0];if(template)return {edit:template.edit,maxEdge:template.maxEdge,...(template.sizes?{sizes:[...template.sizes]}:{}),...(template.qualities?{qualities:[...template.qualities]}:{})};return {edit:provider==='openai'?'mask' as const:'prompt' as const,maxEdge:2048,...(provider==='gemini'?{}:{sizes:[...SIZES]}),...(provider==='openai'||provider==='codex'?{qualities:[...QUALITIES]}:{})};}
function describe(provider:ProviderId,id:string,row:any,known:Model[]):Model{const match=known.find(model=>model.id===id);const label=typeof row?.display_name==='string'&&row.display_name?row.display_name:typeof row?.displayName==='string'&&row.displayName?row.displayName:id;const base=match?{...match,sizes:match.sizes?[...match.sizes]:undefined,qualities:match.qualities?[...match.qualities]:undefined}:{id,label,generate:true,...defaults(provider,known)};return applyOutputOptions(provider,base);}
function dropSnapshots(models:Model[]){const ids=new Set(models.map(model=>model.id));return models.filter(model=>{const snapshot=/^(.*)-\d{4}-\d{2}-\d{2}$/.exec(model.id);return !(snapshot&&ids.has(snapshot[1]));});}
export function parseImageModels(provider:ProviderId,body:unknown,known:Model[]=providers.find(item=>item.id===provider)?.models??[],allImage=false):Model[]{const models:Model[]=[];const seen=new Set<string>();for(const row of rows(body)){const id=modelId(row);if(!keep(provider,row,id,allImage)||seen.has(id))continue;seen.add(id);models.push(describe(provider,id,row,known));for(const alias of Array.isArray(row?.aliases)?row.aliases:[]){if(typeof alias!=='string'||!keep(provider,row,alias,allImage)||seen.has(alias))continue;seen.add(alias);models.push(describe(provider,alias,{...row,display_name:alias,displayName:alias},known));}if(models.length>=80)break;}return dropSnapshots(models).slice(0,80);}
function cleanModel(value:any):Model|undefined{const id=typeof value?.id==='string'?value.id:'';if(!safeId(id))return;const edit=value?.edit==='mask'||value?.edit==='prompt'?value.edit:false;const sizes=Array.isArray(value?.sizes)?value.sizes.filter((item:unknown)=>typeof item==='string'&&SIZE_PATTERN.test(item)).slice(0,48):undefined;const qualities=Array.isArray(value?.qualities)?value.qualities.filter((item:unknown)=>typeof item==='string'&&item.length>0&&item.length<=40).slice(0,16):undefined;const maxEdge=Number(value?.maxEdge);return {id,label:typeof value?.label==='string'&&value.label?value.label.slice(0,200):id,generate:value?.generate!==false,edit,maxEdge:Number.isFinite(maxEdge)&&maxEdge>=64&&maxEdge<=8192?maxEdge:2048,...(sizes?.length?{sizes}:{}),...(qualities?.length?{qualities}:{})};}
export function sanitizeModelCache(value:unknown):Partial<Record<ProviderId,ModelCacheEntry>>{const cache:Partial<Record<ProviderId,ModelCacheEntry>>={};if(!value||typeof value!=='object')return cache;for(const [key,entry] of Object.entries(value as Record<string,any>)){if(!providers.some(provider=>provider.id===key))continue;const fetchedAt=Number(entry?.fetchedAt);const models=Array.isArray(entry?.models)?entry.models.flatMap((item:any)=>{const model=cleanModel(item);return model?[model]:[];}).slice(0,80):[];if(!Number.isFinite(fetchedAt)||fetchedAt<=0||!models.length)continue;cache[key as ProviderId]={fetchedAt,models};}return cache;}
export function customModelsUrl(base:string){try{const url=new URL(base);if(url.protocol!=='https:')return;const path=url.pathname.replace(/\/+$/,'');url.pathname=path.endsWith('/models')?path:`${path}/models`;url.search='';url.hash='';return url.toString();}catch{return;}}
const CODEX_CLIENT_VERSION='0.156.0';
function modelListDenied(error:unknown){return /api\.model\.read|insufficient permissions/i.test(error instanceof Error?error.message:String(error));}
function bearer(accessToken?:string,accountId?:string):Pick<WireRequest,'headers'|'authorization'>{const headers:Record<string,string>={};if(accountId)headers['ChatGPT-Account-Id']=accountId;return {...(Object.keys(headers).length?{headers}:{}),...(accessToken?{authorization:'Bearer '+accessToken}:{})};}
function codexCatalog(accessToken?:string,accountId?:string):Pick<WireRequest,'headers'|'authorization'>{const headers:Record<string,string>={originator:'codex_cli_rs','User-Agent':'codex_cli_rs/'+CODEX_CLIENT_VERSION};if(accountId)headers['ChatGPT-Account-Id']=accountId;return {headers,...(accessToken?{authorization:'Bearer '+accessToken}:{})};}
async function readList(context:AdapterContext,options:WireRequest){return request<any>(context,options,false);}
export async function loadProviderModels(context:AdapterContext,provider:ProviderId,options:{accessToken?:string;accountId?:string;baseUrl?:string}={}):Promise<Model[]>{const known=providers.find(item=>item.id===provider)?.models??[];const authFields=bearer(options.accessToken,options.accountId);const credential=options.accessToken?undefined:provider==='gemini'?auth(context,'x-goog-api-key'):auth(context);
 if(provider==='gemini'){const collected:any[]=[];let page='';for(let attempt=0;attempt<5;attempt++){const body=await readList(context,{url:'https://generativelanguage.googleapis.com/v1beta/models?pageSize=100'+(page?'&pageToken='+encodeURIComponent(page):''),credential});collected.push(...rows(body));page=typeof body?.nextPageToken==='string'?body.nextPageToken:'';if(!page)break;}return parseImageModels(provider,{models:collected},known);}
 if(provider==='custom'){const url=customModelsUrl(options.baseUrl??'');if(!url)return [];return parseImageModels(provider,await readList(context,{url,credential}),known);}
 if(provider==='together')return parseImageModels(provider,await readList(context,{url:'https://api.together.ai/v1/models',credential}),known);
 if(provider==='openai'){try{return parseImageModels(provider,await readList(context,{url:'https://api.openai.com/v1/models',...authFields,credential}),known);}catch(error){if(modelListDenied(error))return [];throw error;}}
 if(provider==='xai'||provider==='grok'){let imageError:unknown;try{const listed=parseImageModels(provider,await readList(context,{url:'https://api.x.ai/v1/image-generation-models',...authFields,credential}),known,true);if(listed.length)return listed;}catch(error){imageError=error;}try{const listed=parseImageModels(provider,await readList(context,{url:'https://api.x.ai/v1/models',...authFields,credential}),known,false);if(listed.length)return listed;}catch(error){throw imageError??error;}throw imageError??new PluginError('MODEL_UNAVAILABLE','The account did not return any image models.');}
 const codexAuth=options.accessToken?undefined:auth(context);let catalogError:unknown;let listed:Model[]=[];try{listed=parseImageModels('codex',await readList(context,{url:'https://chatgpt.com/backend-api/codex/models?client_version='+CODEX_CLIENT_VERSION,...codexCatalog(options.accessToken,options.accountId),credential:codexAuth}),known);}catch(error){catalogError=error;}
 if(listed.length)return listed;if(options.accessToken){if(catalogError&&!modelListDenied(catalogError))throw catalogError;return [];}
 try{const openAi=parseImageModels('codex',await readList(context,{url:'https://api.openai.com/v1/models',credential:codexAuth}),known);if(openAi.length)return openAi;}catch(error){if(modelListDenied(error))return [];throw catalogError??error;}
 throw catalogError??new PluginError('MODEL_UNAVAILABLE','The account did not return any image models.');}
