import type {AdapterContext} from './types';
import type {OAuthProvider,OAuthSession} from './oauth';
import {request} from './common';
export interface QuotaReading {monthly?:number;weekly?:number;fiveHour?:number;credit?:number;}
function num(value:unknown){const n=typeof value==='number'?value:typeof value==='string'?Number(value):NaN;return Number.isFinite(n)?n:undefined;}
function at(body:any,...keys:string[]){let value=body;for(const key of keys){if(!value||typeof value!=='object')return;value=value[key];}return value;}
function remaining(used:number){return Math.round(Math.min(100,Math.max(0,100-used)));}
function windowName(seconds:number):keyof QuotaReading|undefined{if(!(seconds>0))return;if(seconds<=21600)return 'fiveHour';if(seconds<=604800)return 'weekly';if(seconds<=32*24*3600)return 'monthly';}
export function parseCodexQuota(body:any):QuotaReading{const rate=at(body,'rate_limit')??at(body,'rateLimit')??body??{};const windows=[at(rate,'primary_window'),at(rate,'secondary_window'),at(rate,'primaryWindow'),at(rate,'secondaryWindow'),...(Array.isArray(rate?.windows)?rate.windows:[])].filter(item=>item&&typeof item==='object');const reading:QuotaReading={};for(const window of windows){const seconds=num(window.limit_window_seconds??window.limitWindowSeconds);let used=num(window.used_percent??window.usedPercent??window.percent_used);if(used==null){const left=num(window.percent_left??window.remaining_percent);if(left!=null)used=100-left;}if(seconds==null||used==null)continue;const name=windowName(seconds);if(!name||reading[name]!=null)continue;reading[name]=remaining(used);}return reading;}
export function parseGrokQuota(body:any):QuotaReading{const config=body?.config&&typeof body.config==='object'?body.config:body??{};const reading:QuotaReading={};const used=num(config.creditUsagePercent??config.credit_usage_percent);const period=String(config.currentPeriod?.type??config.current_period?.type??'');if(used!=null)reading[/MONTHLY/i.test(period)?'monthly':'weekly']=remaining(used);const limit=num(config.monthlyLimit?.val??config.monthly_limit?.val);const spent=num(config.used?.val);if(reading.monthly==null&&limit!=null&&limit>0&&spent!=null)reading.monthly=remaining(spent/limit*100);const prepaid=num(config.prepaidBalance?.val??config.prepaid_balance?.val);if(prepaid!=null&&reading.monthly==null&&reading.weekly==null)reading.credit=prepaid;return reading;}
export function formatQuota(reading:QuotaReading){const parts=[];if(reading.monthly!=null)parts.push(`Monthly: ${reading.monthly}%`);if(reading.weekly!=null)parts.push(`Weekly: ${reading.weekly}%`);if(reading.fiveHour!=null)parts.push(`5-hour: ${reading.fiveHour}%`);if(parts.length)return parts.join('; ');if(reading.credit!=null)return `Credit: $${reading.credit.toFixed(2)}`;return '';}
export async function loadAccountQuota(context:AdapterContext,provider:OAuthProvider,session:OAuthSession){if(provider==='codex'){const headers:Record<string,string>={};if(session.accountId)headers['ChatGPT-Account-Id']=session.accountId;return formatQuota(parseCodexQuota(await request(context,{url:'https://chatgpt.com/backend-api/wham/usage',headers,authorization:session.accessToken?'Bearer '+session.accessToken:undefined},false)));}return formatQuota(parseGrokQuota(await request(context,{url:'https://cli-chat-proxy.grok.com/v1/billing?format=credits',headers:{'X-XAI-Token-Auth':'xai-grok-cli'},authorization:session.accessToken?'Bearer '+session.accessToken:undefined},false)));}
